matrix:
  include:
    - language: go
      before_script:
        - cd backend
        - go get github.com/gorilla/mux
      script:
        - go test -v data 
        - go test -v server 

    - language: node_js
      before_script:
        - cd frontend 
        - npm install
      script:
        - nmp run test:unit 
        - npm run lint