version: '3'

services:
 frontend:
  build:
   context: ./frontend
   dockerfile: Dockerfile
  restart: always

 backend:
  build:
   context: ./backend
   dockerfile: Dockerfile
  restart: always

  proxy:
    depends_on:
      - backend
      - frontend
    build:
      context: . 
      dockerfile: Dockerfile
    restart: always
    ports: 
      - "80:80"

 

 